### ISSUE TITLE
Running on Homebridge-Docker

### ISSUE THREAD

**Issue by thechrisreese** [homespun/homebridge-platform-ring-video-doorbell#18]
Any thoughts? I am running home bridge in Docker on my NAS getting this error: 

ERROR LOADING PLUGIN homebridge-platform-ring-video-doorbell:                                                                                                   
[2017-9-3 23:17:45] Error: Cannot find module './build/Release/pcap_binding'                                                                                                        
    at Function.Module._resolveFilename (module.js:485:15)                                                                                                                          
    at Function.Module._load (module.js:437:25)                                                                                                                                     
    at Module.require (module.js:513:17)                                                                                                                                            
    at require (internal/module.js:11:18)                                                                                                                                           
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2/index.js:6:22)                                                    
    at Module._compile (module.js:569:30)                                                                                                                                           
    at Object.Module._extensions..js (module.js:580:10)                                                                                                                             
    at Module.load (module.js:503:32)                                                                                                                                               
    at tryModuleLoad (module.js:466:12)                                                                                                                                             
    at Function.Module._load (module.js:458:3)

**Comment by mrose17** [comment]
try `% apt-get install libpcap-dev` on your NAS first... that may do the trick! good luck!

**Comment by thechrisreese** [comment]
I cant seem to get that to work. And installing it on the container service fro my NAS in Docker made everything break.

**Comment by mrose17** [comment]
i think the issue is that you need to get libpcap-dev on your NAS. as to how to do that, i have no idea... sorry!
