### ISSUE TITLE
Error Loading Plugin

### ISSUE THREAD

**Issue by themikea** [homespun/homebridge-platform-ring-video-doorbell#29]
Seeing this at startup of homebridge when trying to use this plugin:
```
homebridge[8849]: [11/01/2018, 15:04:47] ERROR LOADING PLUGIN homebridge-platform-ring-video-doorbell:
homebridge[8849]: [11/01/2018, 15:04:47] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
homebridge[8849]:     at exports.runInThisContext (vm.js:53:16)
homebridge[8849]:     at Module._compile (module.js:373:25)
homebridge[8849]:     at Object.Module._extensions..js (module.js:416:10)
homebridge[8849]:     at Module.load (module.js:343:32)
homebridge[8849]:     at Function.Module._load (module.js:300:12)
homebridge[8849]:     at Module.require (module.js:353:17)
homebridge[8849]:     at require (internal/module.js:12:17)
homebridge[8849]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/index.js:8:19)
homebridge[8849]:     at Module._compile (module.js:409:26)
homebridge[8849]:     at Object.Module._extensions..js (module.js:416:10)
homebridge[8849]:     at Module.load (module.js:343:32)
homebridge[8849]:     at Function.Module._load (module.js:300:12)
homebridge[8849]:     at Module.require (module.js:353:17)
homebridge[8849]:     at require (internal/module.js:12:17)
homebridge[8849]:     at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:22)
homebridge[8849]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:142:14)
```
I'm  running it on an RPi3 running Raspbian Stretch and installed nodejs v4.8.2 installed from the Raspbian repository. And running Homebridge v0.4.35.

**Comment by mrose17** [comment]
sorry for the delay in replying. i have never seen this ... *ever* !!!

is it still happening?
