### ISSUE TITLE
Unable to Install Again

### ISSUE THREAD

**Issue by mkormendy** [homespun/homebridge-platform-ring-video-doorbell#39]
I'm getting the following error when attempting to install this package:

```
npm install --global homebridge-platform-ring-video-doorbell 

> arp-a@0.5.2 install /usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/arp-a
> node-gyp rebuild

  CXX(target) Release/obj.target/macos/src/macos.o
  SOLINK_MODULE(target) Release/macos.node

> socketwatcher@0.3.0 install /usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/socketwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp:77:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(watcher->handle(), callback, argc, argv);
       ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../socket_watcher.cpp:104:37: error: no matching member function for call to 'NewInstance'
    info.GetReturnValue().Set(cons->NewInstance());
                              ~~~~~~^~~~~~~~~~~
/Users/mikey/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/mikey/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
1 warning and 1 error generated.
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/socketwatcher
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socketwatcher@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by reallyjat** [comment]
Same issue here. Perhaps this is a bug with socketwatcher?

**Comment by reallyjat** [comment]
Looks like this:

https://github.com/btrask/node-socketwatcher/issues/18

**Comment by reallyjat** [comment]
I was able to work around this by downgrading to node 8.11.3 instead of 10.7.0.

**Comment by reallyjat** [comment]
Unfortunately it seems that socketwatcher is inactive so I'm not sure who is going to fix the issue there.

**Comment by mkormendy** [comment]
Well I've managed to do a repair patch on the dependencies of this project and got this installed on v10.

I basically forked the base project, and cascade-modified the package.json files to reference forked versions of faulty dependencies that I fixed.

### To Install:

`npm install -g git://github.com/mkormendy/homebridge-platform-ring-video-doorbell.git`

The dependencies I forked and modified are here so you can see the code changes yourself:

https://github.com/mkormendy/homebridge-platform-ring-video-doorbell

https://github.com/mkormendy/homespun-discovery

https://github.com/mkormendy/node-pcap
