### ISSUE TITLE
Lights not working?

### ISSUE THREAD

**Issue by Cardo1** [homespun/homebridge-platform-ring-video-doorbell#41]
Hi all again

I've tried this plugin again today, but whilst all my lights and motion sensors are recognised and appear in HomeKit, unfortunately trying to turn lights on doesn't work.  Homebridge seems to hang a bit and eventually claims the lights are on, but they physically remain off.

Anyone know how to fix this?

**Comment by mrose17** [comment]
sorry for the delay in replying. this is a known issue that i hope to address in two weekends!

**Comment by Cardo1** [comment]
I've tried this out again, but still getting problems with the lights.  Now when I try to turn the lights on, Homebridge crashes with the following error:

/usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/index.js:372
    self.doorbot[value ? 'lightOn' : 'lightOff']({ id: deviceId },
                ^

TypeError: Cannot read property 'lightOn' of undefined
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/index.js:372:17)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by mrose17** [comment]
oops! i have pushed a new version that should fix it, please do

        npm update -g homebridge-platform-ring-video-doorbell

and report back what that says.  you then ought to be able to restart homekit.

sorry!

**Comment by Cardo1** [comment]
The crashing has stopped, but now the device (the floodlight) comes up as not responding when I try to turn it on.

**Comment by Cardo1** [comment]
This is the command that appears in the log...
[8/27/2018, 3:42:12 PM] [Doorbell] setValue { deviceId: 'xxxxxxx' }

**Comment by mrose17** [comment]
thanks. please try again after another

        npm update -g homebridge-platform-ring-video-doorbell

this may not work better, but the logs should be better. thanks!

**Comment by Cardo1** [comment]
And...

[8/27/2018, 5:55:08 PM] [Doorbell] setValue { deviceId: 'xxxxxxx',
  diagnostic: 'Error: not presently connected to service' }

**Comment by Cardo1** [comment]
It seems to be able to read the state of the light, just can't change it.  I turned on the light via the Ring app, and after a few moments, I got 
!!! update Garden: {
  "battery_level": 100,
  "battery_low": 0,
  "reachability": true,
  "floodlight": true,
  "motion_detected": false,
  "ringing": false
}

Trying to turn it off, get the same...
[8/27/2018, 5:58:37 PM] [Doorbell] setValue { deviceId: 'xxxxxxx',
  diagnostic: 'Error: not presently connected to service' }

**Comment by mrose17** [comment]
thanks. OK, one more time with more debug. after doing the 

        npm update -g homebridge-platform-ring-video-doorbell

start homebridge like this:

        DEBUG=ring-video-doorbell

that will get lines printed out like this:

        ring-video-doorbell connecting
        ring-video-doorbell connected +5s

what it looks like is that the plugin doesn't have a connection to the ring server. after you see the "connected" line, then try to toggle the lights.

good luck!

**Comment by Cardo1** [comment]
Unfortunately, I'm not seeing any connecting or connected comments.  I get these:

  ring-video-doorbell after     [] +2ms
  ring-video-doorbell new dings [] +5s
  ring-video-doorbell before    [] +0ms

and when I try to turn the light on:

  ring-video-doorbell after     [] +1ms
[8/27/2018, 7:59:41 PM] [Doorbell] setValue { deviceId: 'xxxxxxx',
  diagnostic: 'Error: not connected for updating floodlight' }
  ring-video-doorbell new dings [] +5s
  ring-video-doorbell before    [] +0ms

**Comment by mrose17** [comment]
thanks. we'll have to put a pin in this until i get my floodlight installed and can test directly... sorry! that's probably about 2-3 weeks out.

**Comment by mrose17** [comment]
Fixed in 0.10.0 ... do `npm update -g homebridge-platform-ring-video-doorbell` and restart homebridge!

**Comment by Cardo1** [comment]
All working now!
