### ISSUE TITLE
RPI2 Install error: pcap/pcap.h: No such file or directory

### ISSUE THREAD

**Issue by atrus05** [homespun/homebridge-platform-ring-video-doorbell#47]
Hardware: Raspberry Pi 2

Issue: Trying to install this plugin from the UI plugin interface (as I am running it in a docker) and I get this error:
```USER: root
DIR: /homebridge
CMD: npm --no-update-notifier install --unsafe-perm --save homebridge-platform-ring-video-doorbell@latest


> socketwatcher@0.3.0 install /homebridge/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function 'static void SocketWatcher::Callback(uv_poll_t*, int, int)':
../socket_watcher.cpp:77:60: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:958:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/homebridge/node_modules/socketwatcher/build'

> pcap@2.0.0 install /homebridge/node_modules/pcap
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
make: *** [pcap_binding.target.mk:94: Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/homebridge/node_modules/pcap/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/pcap
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-29T20_49_22_690Z-debug.log

Command failed. Please review log for details```

I have tried finding some information on it, and I have not been much successful. The one thing that might be the one is that I should install libpcap-dev, but it is installed on the RPI2. I have tried getting into the docker to trigger the same thing in case it needs to be installed inside that as well, but as you might have understood from this... I am very new to docker. I can't figure out how to trigger any install commands after I have entered the Docker running (I enter by running this command vis SSH: docker exec -it homebridge_homebridge_1 /bin/sh

I might be barking up the wrong tree here...

**Comment by mrose17** [comment]
@atrus05 - i think you'll need to talk to the folks doing the UI plugin interface as to how to debug this. my guess is that your docker image is going to need something that includes the libpcap library...
