### ISSUE TITLE
ERR! code 128

### ISSUE THREAD

**Issue by problemss** [homespun/homebridge-platform-ring-video-doorbell#65]
I saw several other posts on this error, but their solutions did not work for me. I installed libpcap-dev successfully and ran sudo npm i -g npm and it is still not working. Here is my error
`sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-4ec0af2c': Permission denied
npm ERR!
`
Here is my log contents
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-platform-ring-video-doorbell' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose npm-session d7484b38a24ab77e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-platform-ring-video-doorbell 449ms (from cache)
8 silly pacote tag manifest for homebridge-platform-ring-video-doorbell@latest fetched in 751ms
9 timing stage:loadCurrentTree Completed in 3685ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 6ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 50ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-platform-ring-video-doorbell@0.12.1 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/doorbot 742ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/homespun-utilities 656ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/underscore 656ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/debug 880ms (from cache)
21 silly pacote range manifest for doorbot@^5.4.0 fetched in 947ms
22 silly resolveWithNewModule doorbot@5.4.0 checking installable status
23 silly pacote version manifest for homespun-utilities@0.3.1 fetched in 877ms
24 silly resolveWithNewModule homespun-utilities@0.3.1 checking installable status
25 silly pacote version manifest for underscore@1.8.3 fetched in 880ms
26 silly resolveWithNewModule underscore@1.8.3 checking installable status
27 silly pacote range manifest for debug@~2.6.9 fetched in 1060ms
28 silly resolveWithNewModule debug@2.6.9 checking installable status
29 silly fetchPackageMetaData error for hap-nodejs-community-types@git+https://github.com/homespun/hap-nodejs-community-types.git Command failed: /usr/bin/git submodule update -q --init --recursive
29 silly fetchPackageMetaData fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-c6bbbe7e': Permission denied
30 timing stage:rollbackFailedOptional Completed in 60ms
31 timing stage:runTopLevelLifecycles Completed in 8821ms
32 verbose stack Error: Command failed: /usr/bin/git submodule update -q --init --recursive
32 verbose stack fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-c6bbbe7e': Permission denied
32 verbose stack
32 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
32 verbose stack     at ChildProcess.emit (events.js:188:13)
32 verbose stack     at maybeClose (internal/child_process.js:978:16)
32 verbose stack     at Socket.stream.socket.on (internal/child_process.js:395:11)
32 verbose stack     at Socket.emit (events.js:188:13)
32 verbose stack     at Pipe._handle.close (net.js:610:12)
33 verbose cwd /home/pi
34 verbose Linux 4.4.50+
35 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-platform-ring-video-doorbell"
36 verbose node v11.6.0
37 verbose npm  v6.5.0-next.0
38 error code 128
39 error Command failed: /usr/bin/git submodule update -q --init --recursive
39 error fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-c6bbbe7e': Permission denied
40 verbose exit [ 1, true ]
`

**Comment by problemss** [comment]
FYI, after doing some research it appears to be an issue with NPM as it uses the UID of the parent process even when I call `sudo`. So I had to use `sudo su` and then run `sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell` and it appears to have installed successfully.
