### ISSUE TITLE
Ring Pro 

### ISSUE THREAD

**Issue by AndrewVIsh** [homespun/homebridge-platform-ring-video-doorbell#74]
Can you help?
Getting an error when runing homebridge

[6/13/2019, 9:34:15 PM] [homebridge-ring-alarm.RingAlarm] Error connecting to API
[6/13/2019, 9:34:15 PM] [homebridge-ring-alarm.RingAlarm] TypeError: Cannot read property 'email' of null
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring-alarm/api/index.js:20:69)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring-alarm/api/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring-alarm/api/index.js:3:12)
    at Object.getLocations (/usr/local/lib/node_modules/homebridge-ring-alarm/api/index.js:19:12)
    at RingAlarmPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:77:43)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:7:71
    at new Promise (<anonymous>)

**Comment by gilbert76** [comment]
Please check Your Config.json, because the field with email address is incorrect or empty or doesn’t exist.

**Comment by AndrewVIsh** [comment]
{
	"bridge": {
		"name": "Homebridge",
		"username": "xxx",
		"port": 51826,
		"pin": "000-00-xxx"
	},

	"platform": "ring-video-doorbell",
	"name": "Front Door",
	"username": "xxxxx",
	"password": "xxxx"

		,
	"options": {
		"retries": 5,
		"ttl": 5,
		"verboseP": false
	},
	"ringing": {
		"event": "single",
		"motion": false,
		"contact": false
	}
}


xxx is my username and password. I am using homebridge on mac dose that make a difference ?

**Comment by gilbert76** [comment]
Username and password from Ring.com account

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
